---
- include_vars: 
    file: vars.yml

- name: "Install Rack required for Passenger"
  shell: >
    ls {{ rvm_dir }}/wrappers/{{ ruby_version }}
    | if ! grep "^rackup " ; then {{ rvm_dir }}/wrappers/{{ ruby_version }}/gem install rack -v=1.6.5 ; fi
  register: rack_install
  args:
    creates: "{{ rvm_dir }}/gems/{{ ruby_version }}/bin/rackup"
  changed_when: '"Successfully installed rack" in rack_install.stdout'

- name: "Install Passenger"
  shell: >
    ls {{ rvm_dir }}/wrappers/{{ ruby_version }}/
    | if ! grep "^passenger$" ; then {{ rvm_dir }}/wrappers/{{ ruby_version }}/gem install passenger ; fi
  register: pass_install
  args:
    creates: "{{ rvm_dir }}/gems/{{ ruby_version }}/bin/passenger"
  changed_when: '"Successfully installed passenger" in pass_install.stdout'

- name: Check passenger version
  shell: >
    {{ rvm_dir }}/wrappers/{{ ruby_version }}/passenger -v | awk '{print $NF}'
  register: pass_version

- name: Check apache is alreay compile or not
  stat: "path={{ rvm_dir }}/gems/{{ ruby_version }}/gems/passenger-{{ pass_version.stdout }}/buildout/apache2/mod_passenger.so"
  register: apache_compile

- name: Install and configure apache
  shell: >
    {{ rvm_dir }}/wrappers/{{ ruby_version }}/passenger-install-apache2-module --auto
  register: apache_install
  args:
    creates: "{{ rvm_dir }}/gems/{{ ruby_version }}/gems/passenger-{{ pass_version.stdout }}/buildout/apache2/mod_passenger.so"
  when: apache_compile.stat.exists != True 
  changed_when: '"Detected 0 error" in apache_install.stdout'
